from __future__ import annotations

ARCHITECTURE_TREES = [
    {
        "id": "control",
        "title": "Control + Heartbeat Tree",
        "color": "#6ea8fe",
        "nodes": [
            {
                "id": "ui",
                "title": "Control Panel / Dashboard",
                "subtitle": "web UI, commands, agents, projects, architecture explorer",
                "kind": "component",
                "scripts": ["app.py", "views.py", "templates/base.html", "static/control_panel.css", "static/architecture.js"],
                "details": [
                    "Front door for managing agents, heartbeat, tracked paths, project tracker, and commands.",
                    "Hosts the architecture explorer and script inventory.",
                ],
            },
            {
                "id": "heartbeat_global",
                "title": "Global Heartbeat Policy",
                "subtitle": "HEARTBEAT.md + global cadence / mode rules",
                "kind": "policy",
                "scripts": ["HEARTBEAT.md"],
                "details": [
                    "Defines global memory-system operating rules, cadence, and required update behavior.",
                ],
            },
            {
                "id": "heartbeat_agents",
                "title": "Agent Heartbeat / Role Rules",
                "subtitle": "HEARTBEAT_AGENTS.md + policy enforcement",
                "kind": "policy",
                "scripts": ["HEARTBEAT_AGENTS.md", "check_agent_memory_policy.py"],
                "details": [
                    "Controls agent-level routing ceilings, heartbeat expectations, and approval boundaries.",
                ],
            },
        ],
        "edges": [
            ("ui", "heartbeat_global", "configure"),
            ("heartbeat_global", "heartbeat_agents", "specialize"),
        ],
    },
    {
        "id": "ingest",
        "title": "Ingest + Dehydrate Tree",
        "color": "#4dd4ac",
        "nodes": [
            {
                "id": "transcript_sources",
                "title": "Transcript / Session Sources",
                "subtitle": "raw session text, agent output, workspace state",
                "kind": "source",
                "scripts": [],
                "details": ["Entry point for newly generated session material before memory extraction."],
            },
            {
                "id": "dehydrate",
                "title": "Dehydrate Transcript",
                "subtitle": "strip noise, normalize transcript structure",
                "kind": "pipeline",
                "scripts": ["dehydrate_transcript.py"],
                "details": ["Removes low-value transcript clutter and prepares durable content for chunking."],
            },
            {
                "id": "chunking",
                "title": "Chunk + Update Extraction",
                "subtitle": "topic chunking and change extraction",
                "kind": "pipeline",
                "scripts": ["chunk_by_topic.py", "extract_chunk_updates.py"],
                "details": ["Splits transcript into topic chunks and extracts candidate memory updates."],
            },
            {
                "id": "filter_judge",
                "title": "Filter + Judge Candidates",
                "subtitle": "field extraction, scope, confidence, route hint",
                "kind": "pipeline",
                "scripts": ["filter_memory_candidates.py", "judge_memory_candidates.py", "extract_memory_fields.py"],
                "details": [
                    "Rejects vague/raw blobs and rewrites good candidates into atomic memory facts.",
                    "Assigns memory_type, scope, entity, property, value, and suggested_route.",
                ],
            },
        ],
        "edges": [
            ("transcript_sources", "dehydrate", "clean"),
            ("dehydrate", "chunking", "chunk"),
            ("chunking", "filter_judge", "judge"),
        ],
    },
    {
        "id": "routing",
        "title": "Routing + Review Tree",
        "color": "#ffd166",
        "nodes": [
            {
                "id": "route_single",
                "title": "Single / Batch Routing",
                "subtitle": "route to inbox, discarded, pending stable, auto",
                "kind": "pipeline",
                "scripts": ["route_memory_item.py", "route_memory_items_batch.py"],
                "details": ["Places judged items into queues using confidence, scope, importance, and policy ceilings."],
            },
            {
                "id": "queue_inbox",
                "title": "memory_inbox",
                "subtitle": "review queue",
                "kind": "queue",
                "scripts": [],
                "details": ["DB queue for memories requiring manual review or later resolution."],
            },
            {
                "id": "queue_pending",
                "title": "memory_pending_stable",
                "subtitle": "approval gate for strong stable memory",
                "kind": "queue",
                "scripts": [],
                "details": ["DB queue for high-confidence stable memories awaiting explicit approval."],
            },
            {
                "id": "queue_discarded",
                "title": "memory_discarded",
                "subtitle": "discard history and reject cache",
                "kind": "queue",
                "scripts": [],
                "details": ["DB discard cache used to block repeated junk or rejected memories."],
            },
            {
                "id": "approval_ops",
                "title": "Approval / Lifecycle Ops",
                "subtitle": "approve, reject, promote, demote, restore, auto-process",
                "kind": "pipeline",
                "scripts": [
                    "approve_pending_memory_item.py",
                    "reject_pending_memory_item.py",
                    "promote_memory_item.py",
                    "demote_memory_item.py",
                    "restore_memory_item.py",
                    "auto_promote_safe_items.py",
                    "process_auto_memory_items.py",
                ],
                "details": ["Moves memories across lifecycle states and applies stable promotion policy."],
            },
        ],
        "edges": [
            ("route_single", "queue_inbox", "review"),
            ("route_single", "queue_pending", "stable gate"),
            ("route_single", "queue_discarded", "reject"),
            ("queue_pending", "approval_ops", "approve/reject"),
            ("queue_inbox", "approval_ops", "promote/demote"),
        ],
    },
    {
        "id": "canonical",
        "title": "Canonical Registry Tree",
        "color": "#c084fc",
        "nodes": [
            {
                "id": "registry_write",
                "title": "Canonical Write Path",
                "subtitle": "select best, reconcile, patch, and write canonical memory",
                "kind": "pipeline",
                "scripts": [
                    "write_memory_item.py",
                    "select_best_registry_item.py",
                    "match_memory_items.py",
                    "reconcile_memory_items.py",
                    "patch_memory_file.py",
                ],
                "details": ["Chooses best matching canonical row, merges or supersedes, then writes canonical state."],
            },
            {
                "id": "registry_db_api",
                "title": "memory_db.py",
                "subtitle": "DB API for items, queues, feedback, embeddings, search",
                "kind": "database",
                "scripts": ["memory_db.py"],
                "details": ["Database access layer used by routing, retrieval, feedback, maintenance, and embedding workflows."],
            },
            {
                "id": "memory_items_table",
                "title": "memory_items",
                "subtitle": "canonical active / superseded / archived / uncertain rows",
                "kind": "database",
                "scripts": [],
                "details": ["Primary canonical DB table for durable memory state."],
            },
            {
                "id": "markdown_sync",
                "title": "Markdown Sync + Human Files",
                "subtitle": "sync registry back to readable memory markdown",
                "kind": "pipeline",
                "scripts": ["sync_registry_to_markdown.py", "report_memory_maintenance.py"],
                "details": ["Creates and maintains readable markdown mirrors such as browser.md, preferences.md, memory-system.md."],
            },
        ],
        "edges": [
            ("registry_write", "registry_db_api", "upsert"),
            ("registry_db_api", "memory_items_table", "store"),
            ("memory_items_table", "markdown_sync", "sync"),
        ],
    },
    {
        "id": "retrieval",
        "title": "Retrieval + Tensor Tree",
        "color": "#2dd4bf",
        "nodes": [
            {
                "id": "embedding_path",
                "title": "Tensor / Embedding Path",
                "subtitle": "Sentence-Transformers all-MiniLM-L6-v2 encoding",
                "kind": "tensor",
                "scripts": ["embed_memory_items.py"],
                "details": ["Encodes active canonical memory rows into normalized vectors for hybrid retrieval."],
            },
            {
                "id": "embeddings_table",
                "title": "memory_item_embeddings",
                "subtitle": "vector table for pgvector-backed similarity search",
                "kind": "tensor",
                "scripts": [],
                "details": ["Stores normalized embedding vectors keyed by memory row and model."],
            },
            {
                "id": "hybrid_search",
                "title": "Hybrid Search Layer",
                "subtitle": "FTS + vector score + structured bonuses + RBAC",
                "kind": "pipeline",
                "scripts": ["search_memory.py", "search_memory_rbac.py", "memory_access_policy.py", "test_hybrid_search.py"],
                "details": [
                    "Ranks memories using full-text search, vector similarity, structure overlap, and importance weighting.",
                    "RBAC path filters by sensitivity.",
                ],
            },
            {
                "id": "retrieval_feedback_table",
                "title": "retrieval_feedback",
                "subtitle": "useful/bad operator judgments for ranking adaptation",
                "kind": "database",
                "scripts": [],
                "details": ["Stores retrieval outcome judgments that feed ranking bonuses and penalties."],
            },
            {
                "id": "feedback_loop",
                "title": "Retrieval Feedback Loop",
                "subtitle": "mark useful/bad, adjust ranking, inspect low utility",
                "kind": "pipeline",
                "scripts": [
                    "mark_retrieval_useful.py",
                    "mark_retrieval_bad.py",
                    "apply_feedback_actions.py",
                    "report_feedback_actions.py",
                    "show_low_utility_retrievals.py",
                    "show_top_retrieved.py",
                ],
                "details": ["Collects ranking signals and applies penalty/bonus logic to future retrieval behavior."],
            },
        ],
        "edges": [
            ("embedding_path", "embeddings_table", "embed"),
            ("embeddings_table", "hybrid_search", "vector rank"),
            ("hybrid_search", "retrieval_feedback_table", "log outcome"),
            ("retrieval_feedback_table", "feedback_loop", "feedback"),
            ("feedback_loop", "hybrid_search", "tune rank"),
        ],
    },
    {
        "id": "ops",
        "title": "Inspection + Migration Tree",
        "color": "#fb7185",
        "nodes": [
            {
                "id": "maintenance",
                "title": "Maintenance / Report Surface",
                "subtitle": "queue, maintenance, conflicts, recent writes, promotion views",
                "kind": "pipeline",
                "scripts": [
                    "show_review_queue.py",
                    "report_memory_maintenance.py",
                    "show_conflicts.py",
                    "show_conflict_candidates.py",
                    "show_superseded.py",
                    "show_recent_writes.py",
                    "show_demotion_candidates.py",
                    "show_promotion_candidates.py",
                    "why_was_this_written.py",
                    "why_was_this_retrieved.py",
                    "report_semantic_conflicts.py",
                    "report_promotion_candidates.py",
                ],
                "details": ["Operational console for inspecting current queues, semantic conflicts, promotions, and recent writes."],
            },
            {
                "id": "migrations",
                "title": "Migration / Backfill Utilities",
                "subtitle": "legacy JSONL to DB and feedback migration",
                "kind": "pipeline",
                "scripts": ["migrate_jsonl_to_db.py", "migrate_review_queues_to_db.py", "migrate_feedback_and_insights_to_db.py"],
                "details": ["Moves legacy JSONL state into the DB-backed registry and feedback system."],
            },
            {
                "id": "projects",
                "title": "Project File Memory",
                "subtitle": "current.md, milestones, daily notes, tracked project files",
                "kind": "project",
                "scripts": ["memory/projects/*/current.md", "memory/projects/*/milestone-*.md", "memory/projects/*/daily/*.md"],
                "details": ["Project-scoped memory stored in markdown and surfaced through the control panel and search layer."],
            },
            {
                "id": "inventory",
                "title": "Full Script Inventory",
                "subtitle": "all scripts in .memory-index/scripts grouped automatically",
                "kind": "inventory",
                "scripts": [],
                "details": ["Live-generated inventory of all scripts in the scripts directory, including anything not hand-mapped."],
            },
        ],
        "edges": [
            ("maintenance", "migrations", "backfill"),
            ("maintenance", "projects", "inspect"),
            ("maintenance", "inventory", "catalog"),
        ],
    },
]

ARCHITECTURE_CROSS_EDGES = [
    ("ui", "transcript_sources", "monitor"),
    ("heartbeat_agents", "filter_judge", "policy ceiling"),
    ("filter_judge", "route_single", "judge output"),
    ("approval_ops", "registry_write", "approved write"),
    ("memory_items_table", "hybrid_search", "retrieve"),
    ("memory_items_table", "embedding_path", "embed source"),
    ("projects", "hybrid_search", "file search"),
    ("hybrid_search", "maintenance", "report"),
    ("memory_items_table", "maintenance", "inspect"),
]
