"""
Pydantic models for memory routing — defines schemas for routing decisions,
scope assignments, and pipeline metadata.
"""
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class MemoryScopeLevel(str, Enum):
    """
    Explicit memory scopes defining the breadth and durability of context.
    """
    GLOBAL = "GLOBAL"
    # Whole game (pillars, architecture, naming, combat philosophy, engine constraints, etc.). Stable/Broad.

    SUBPROJECT = "SUBPROJECT"
    # Major subsystem (combat, AI, UI, level gen, etc.). Narrower/Mutable.

    WORK_ITEM = "WORK_ITEM"
    # Active task tree (e.g., "patrol alert escalation pass"). Highly local.

    EPHEMERAL = "EPHEMERAL"
    # Current run only (assumptions, local experiment notes). Never automatically durable.


class MemoryReference(BaseModel):
    """
    A reference to a specific piece of memory, including its origin and selection reasoning.
    Required by Deliverable 3 (each child must store inherited memory refs, inherited scope level, 
    and *why* each ref was selected).
    """
    memory_id: str = Field(..., description="Unique identifier for the memory entry.")
    scope: MemoryScopeLevel = Field(..., description="The scope level this memory belongs to.")
    reason_for_selection: str = Field(
        ..., 
        description="Explanation of why this memory ref was included (crucial for debugging)."
    )


class WorkItemMemoryMetadata(BaseModel):
    """
    Memory metadata attached to a specific WorkItem, defining its hierarchical 
    context and memory references.
    
    Implements Feature A: Memory scope object.
    """
    project_id: str = Field(
        ..., 
        description="The ID of the global project."
    )
    subproject_id: Optional[str] = Field(
        default=None, 
        description="The ID of the subproject, if applicable."
    )
    parent_work_id: Optional[str] = Field(
        default=None, 
        description="The ID of the parent work item, if applicable."
    )
    
    memory_scope: MemoryScopeLevel = Field(
        default=MemoryScopeLevel.WORK_ITEM,
        description="The primary operational scope level of this work item."
    )
    
    inherited_memory_refs: List[MemoryReference] = Field(
        default_factory=list,
        description="Memory references inherited from parent, subproject, or global scopes."
    )
    
    promoted_memory_refs: List[MemoryReference] = Field(
        default_factory=list,
        description="Memory references generated by this work item that have been successfully promoted to a broader scope."
    )
    
    local_memory_refs: List[MemoryReference] = Field(
        default_factory=list,
        description="Memory references tightly local to this specific work item (not promoted)."
    )
